# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="kechja"
# Fancy them with powerline
#ZSH_THEME="agnoster"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"
# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13
# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"
# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"
# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"
# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"
# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
# /opt/ paths are for Macports
#export PATH=/opt/local/bin:/opt/local/sbin:/usr/local:$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

#MACPORTS USES THE EDITOR VARIABLE
# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='mvim'
 fi
#export VIM=$HOME/.vim
#
#GREP
#Shell Colors
#Color	Foreground	Background
#Black	    30	               40
#Red	    31	               41
#Green	    32	               42
#Yellow	    33	               43
#Blue	    34	               44
#Magenta    35	               45
#Cyan	    36	               46
#White	    37	               47
export GREP_COLOR="01;30;1;41"
#Use extended regex, color, and search case insensitive.
export GREP_OPTIONS='--color=auto'
alias grep="grep -P"
alias irb="irb --simple-prompt"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"
# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

#HISTORY SETTINGS
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
HISTIGNORE="ls:ls -l:ls -la:cd :cd .."  #Note - this only works in bash.
HISTSIZE=100 #Number of lines in the history file.
SAVEHIST=50 #Number of lines to be saved from the session.

#ALIASES
alias ll='ls -laF'
alias la='ls -la'
alias showhidden='defaults write com.apple.finder AppleShowAllFiles 1 && killall Finder'
alias hidehidden='defaults write com.apple.finder AppleShowAllFiles 0 && killall Finder'
alias -s txt="open -a textwrangler"
alias ff="open -a firefox"
alias e='open -a macvim'
alias sd="sudo shutdown -h now"
alias tree="tree -F"
alias gg='ts;ff'
alias music='open /Volumes/Data/KJ\ Music'
alias ms='osascript /usr/local/bin/mount_server.scpt 2>/dev/null'
alias email='open -a thunderbird'
alias prog='cd /Volumes/Data/KJ_Records/3_Work/Programming'
alias got='git'

#SYNTAX HIGHLIGHTING NEEDS TO RUN *BEFORE* SUB-STRING SEARCH
#TEST - SYNTAX HIGHLIGHTING - DIDN'T WORK
DEBIAN_PREVENT_KEYBOARD_CHANGES=yes
#ZSH_CUSTOM=~/.oh-my-zsh/custom/
#plugins=(history-substring-search zsh-syntax-highlighting)
#DIDN-T WORK: plugins=~/.oh-my-zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

#HISTORY SUB-STRING SEARCH
#source ~/.zsh-hist-sub-search/zsh-hist-sub-search.zsh
#bindkey -M emacs '^P' history-substring-search-up		# bind P and N for EMACS mode
#bindkey -M emacs '^N' history-substring-search-down		# bind P and N for EMACS mode
#bindkey -M vicmd 'k' history-substring-search-up 		# bind k and j for VI mode
#bindkey -M vicmd 'j' history-substring-search-down		# bind k and j for VI mode
#bindkey '^[[A' history-substring-search-up                      # bind UP and DOWN arrow keys
#bindkey '^[[B' history-substring-search-down			# bind UP and DOWN arrow keys

#ENABLING <C-S> FOR VIM
#stty sets options for the Terminal program.
#-ixon toggles Terminal's use of <c-s> & <c-q> for scrolling overflow.
#This is legacy, but if you're terminal's locked up, with ix activated you get your terminal back with those keys.
stty -ixon

#ZCALC
#remembers your variables in $1, $2, etc; use "ans" for last result 
autoload zcalc


#Setup RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

