# ZSH SOURCE #
##############

# ZSH PATH
export ZSH="/Users/kevin/.oh-my-zsh"

# THEME
ZSH_THEME="agnoster"

# PLUGINS
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# USER CONFIGURATION #
######################

# VIM BINDINGS  
set -o vi

# HISTORY SETTINGS
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
HISTSIZE=10000 #Number of lines in the history file.
SAVEHIST=10000 #Number of lines to be saved from the session.

# ALIASES
alias dt='cd ~/Desktop'
alias e='open -a macvim'
alias em='open -a thunderbird'
alias ff="open -a firefox"
alias fnl='open /Volumes/Data/KJ_Records/4_Things/Property/Financials/2018_financials.ods'
alias got='git '
alias gti='git '
alias la='ls -la'
alias ld='find * -d 0 -type d 2> /dev/null'
alias lf='find * -d 0 -type f 2> /dev/null'
alias ll='ls -laF'
alias man='gem man -s'
alias pip='pip3'
alias python='python3'
alias qb='open /Volumes/Data/KJ_Records/4_Things/Property/Financials/quickbooks/Kevin\ Jackson.qb2016' 
alias tree="tree -F"
alias xc="open -a xcode"
